### ISSUE TITLE
"Select an IP address or all IP addresses to be used for the ASDs" when only having 1 IP

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#118]
The first question for IP takes exacly one choice, the other we have to choose between the single ip and all.

```
+++++++++++++++++++++++++++
+++  ASD Manager setup  +++
+++++++++++++++++++++++++++
- Verifying distribution
Found exactly one choice: 172.19.5.31
Select the port to be used for the API [8500]: 
Select an IP address or all IP addresses to be used for the ASDs. Make a selection please: 
    1: 172.19.5.31
    2: All
  Select Nr:  [2]: 1
Do you want to add another IP? (y/n): n
```

**Comment by khenderick** [comment]
The first question is about which IP to use for API communications; you have to select one.
The other question is about on which IP addresses the ASDs should listen; you can select one or more, or "all" meaning that no ip address will be specified and Alba figures out the connectivity itself.

So everything looks "as expected" to me. What behavior would you expect?

**Comment by kinvaris** [comment]
In the first question, if a single ip address is detected. It just takes that ip address.
In the second question there is asked: `Select an IP address or all IP addresses to be used for the ASDs. Make a selection please:`
But with 1 ip address we don't want to make a selection. This has to be consistent between the questions.

**Comment by khenderick** [comment]
There's still a difference. The one ip address means: only use that one ip address and never ever use anything else. ```All``` means; the ASD can just choose whatever he wants, so if you in the future would add an ip address, it might as well start using that one.

**Comment by kinvaris** [comment]
Then I think that `All` is not a good description you are giving to the customer. I think more feasible would be `All current and future interfaces` or with a more technical description, will use `0.0.0.0`.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/alba-asdmanager/pull/212 --> openvstorage-sdm-1.6.11-dev.1484905907.d4383c0

**Comment by khenderick** [comment]
openvstorage-sdm-1.6.11.1
