### ISSUE TITLE
All ASD services are down after a reboot on 16.04

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#132]
After a reboot on a ovs node with 16.04 installed we observed the following:
- The ASD watcher and manager were running correctly
- No ASDs were running

```
root@stor-01:~# systemctl status alba-asd-2bgBSYhWKf1vUiDUpN263zlQ16D83kFm.service
● alba-asd-2bgBSYhWKf1vUiDUpN263zlQ16D83kFm.service - "alba asd"
   Loaded: loaded (/lib/systemd/system/alba-asd-2bgBSYhWKf1vUiDUpN263zlQ16D83kFm.service; static; vendor preset: enabled)
   Active: inactive (dead)
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1103
https://github.com/openvstorage/alba-asdmanager/pull/141

**Comment by pploegaert** [comment]
PASSED: all asd services were running on each node (3 node setup)

ran ci.tests.vdisk test suite before / after reboot

testsuite did run ok
