### ISSUE TITLE
asd monitor services are displaying wrong information on 16.04

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#134]
asd monitor services are displaying wrong information:
some services are missing but are available in `/lib/systemd/system`
Example to display running & non-running services in systemd

```
echo -e "\nASD Manager running processes:\n"; for i in $(systemctl list-unit-files | grep "alba\|asd" | grep -v "ovs-" | tr -s ' ' | cut -d ' ' -f 1); do if [ $(systemctl is-active ${i}) == 'active' ]; then echo ${i}; fi; done;echo -e "\nASD Manager non-running processes:\n"; for i in $(systemctl list-unit-files | grep "alba\|asd" | grep -v "ovs-" | tr -s ' ' | cut -d ' ' -f 1); do if [ $(systemctl is-active ${i}) == 'inactive' ]; then echo ${i}; fi; done
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1100 --> 
https://github.com/openvstorage/alba-asdmanager/pull/139 --> openvstorage-sdm-1.6.4-rev.404.cb389b1

**Comment by kvanhijf** [comment]
@QA: All services should now be properly displayed on ubuntu 16.04 for both
```
asd-manager monitor services
```
and
```
ovs monitor services
```
Stopping / disabling services should result in those services popping up in the non-running processes section

**Comment by kvanhijf** [comment]
Incomplete, noticed that stopping the maintenance services, doesn't show them in non-running processes

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1107 --> openvstorage-2.7.4-rev.4241.ac52433
https://github.com/openvstorage/alba-asdmanager/pull/143 --> openvstorage-sdm-1.6.4-rev.412.7a2713e

**Comment by kinvaris** [comment]
PASSED:
Processes will now be displayed even when they are inactive, disabled, crashed, ...

```
asd-manager monitor services

ASD Manager running processes
=============================

asd-manager  active
asd-watcher  active


ASD Manager non-running processes
=================================

ovs monitor services

OVS running processes
=====================

ovs-arakoon-config         active
ovs-arakoon-ovsdb          active
ovs-scheduled-tasks        active
ovs-support-agent          active
ovs-volumerouter-consumer  active
ovs-watcher-config         active
ovs-watcher-framework      active
ovs-webapp-api             active
ovs-workers                active


OVS non-running processes
=========================

```
