### ISSUE TITLE
ASDmanager package not updateable

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/alba-asdmanager#169]
Due to changes in our SSHClient, the ASDmanager package is not updateable
In /opt/asd-manager/source/controllers/update.py
on line 97
```
UpdateController._local_client.run(['at', '-f', '/tmp/update now'])
```

should become
```
UpdateController._local_client.run(['at', '-f', '/tmp/update', 'now'])
```

Due to this, the offloading of the update always fails and thus the packages never get updated

**Comment by kvanhijf** [comment]
Unstable --> openvstorage-sdm-1.6.7-rev.457.f5194fe
Fargo -->

**Comment by pploegaert** [comment]
VALIDATED OK
