### ISSUE TITLE
Introduce run files for ASD processes and maintenance processes

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/alba-asdmanager#180]
In case an update of the SDM package failed for some reason, but the packages have been updated, the update logic cannot detect certain services still need to be restarted. Similar to the run files for alba and arakoon, we should have this for the ASDs and maintenance too. With these files in place, the update logic can detect some services still need a restart and thus reporting 'Updates Available' in the GUI

PS: Perhaps we also need to expand this for more framework services too?

**Comment by khenderick** [comment]
It's a bug, not a feature, as this prevents us from properly detecting a service still needs to be restarted.

**Comment by wimpers** [comment]
This one is related to https://github.com/openvstorage/framework/issues/1225 ?

**Comment by kvanhijf** [comment]
Not really
#1225 is about being able to coop with changes in service files during the update
This ticket is detecting whether a restart of certain services is required

They're only related in a way that they both have something to do with the update

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1258 --> openvstorage-2.7.8-rev.4426.798b62a
https://github.com/openvstorage/alba-asdmanager/pull/187 --> openvstorage-sdm-1.6.8-rev.491.b750c03
https://github.com/openvstorage/framework-alba-plugin/pull/304 --> openvstorage-backend-1.7.8-rev.868.fe03d1f

**Comment by kvanhijf** [comment]
@QA: Version runfiles have been introduced for
ASDs (/opt/asd-manager/run/alba-asd-<id>.version
Maintenance (/opt/asd-manager/run/alba-maintenance_<backend_name>-<id>.version
Volumedriver (/opt/OpenvStorage/run/volumedriver_<vpool_name>.version
DTL (/opt/OpenvStorage/run/dtl_<vpool_name>.version

Changing the version numbers in any of these files should result in an available update on the node hosting the file (When clicking 'Refresh' in the Updates page in the GUI)

Also updating the related package of the service, should result in the latest version being displayed in the run file
eg: updating volumedriver-no-dedup-server should result in both the volumedriver and dtl runfiles to contain the installed version of the package (volumedriver_fs --version)

**Comment by pploegaert** [comment]
VALIDATED OK
