### ISSUE TITLE
Add validation for 'at' functionality

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/alba-asdmanager#191]
In the framework code we have some code validating the 'at' functionality, which the update relies on
In the ASD-manager code we should have the same functionality. Without this validation, the update might succeed, but will actually do nothing and also report nothing, so the updates will remain visible in the GUI

**Comment by wimpers** [comment]
After discussion with @khenderick about the impact of this issue, set to normal enhancement. Happens when the at functionality is messed up (which should not be the case).

**Comment by kvanhijf** [comment]
Ticket no longer applicable
Ticket was created at the time we used 'at' to install the SDM packages, but this is no longer the case since the rework of the update. The packages are now being installed making use of the ASDManagerClient which waits for each package to install.
