### ISSUE TITLE
Implement 'asd-manager collect logs' identical to the 'ovs collect logs'

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/alba-asdmanager#199]
We don't have a way to retrieve the logs related to ASD actions. We should also be able to collect the logs, on pure storagenodes, remotely

**Comment by wimpers** [comment]
@jeroenmaelbrancke do we already collect the ASD manager logs as part of the https://github.com/openvstorage/openvstorage-monitoring project?

**Comment by jeroenmaelbrancke** [comment]
Yep, Journalbeat capture all the logs being sent to journalctl.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1335 --> openvstorage-2.7.10-dev.1484238842.9c65b08
https://github.com/openvstorage/alba-asdmanager/pull/205 --> openvstorage-sdm-1.6.10-dev.1484238397.2dd02ed
https://github.com/openvstorage/framework-alba-plugin/pull/332 --> openvstorage-backend-1.7.10-dev.1484238920.470b79c

@QA:
New API has been introduced to collect the logfiles for the ASD manager
`api.get('/alba/nodes/<node_guid>/get_logfiles')`

In the support page, you can also see the nodes, which are not linked to a StorageRouter to collect and download the logfiles from

All downloaded logs should still end up in /opt/OpenvStorage/webapps/frontend/downloads on the node running the GUI

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-sdm-1.6.10.1

**Comment by pploegaert** [comment]
VALIDATION OK
asd-manager collect logs -> ends up in /opt/asd-manager/downloads
