### ISSUE TITLE
State on the ASD-manager

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba-asdmanager#231]
We need some kind of DB on the node. This could be either something like sqlite (and we write a wrapper to perform basic queries), or leveldb (we can pull the DAL out of the framework, make it a standalone library and use it in both framework and alba-asdmanager).
* Sqlite might be the fastest option here

Make an update that models everything in the above

**Comment by khenderick** [comment]
openvstorage-sdm-1.7.2-dev.1491916176.0023797

**Comment by khenderick** [comment]
Packages in 1.9.0

**Comment by wimpers** [comment]
Closed by PM.
