### ISSUE TITLE
asd-manager/watcher standard/default log level is debug

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba-asdmanager#257]
Why are the loglevels of the asd-manager/watcher debug?
Can you please change this to info when you release the package?

```
June 21st 2017, 09:11:46.663	NY1SRV0001	asd-manager.service	asd-manager/api	DEBUG	GET /maintenance - Leaving
June 21st 2017, 09:11:46.692	NY1SRV0001	asd-manager.service	asd-manager/api	DEBUG	GET /service_status/<name> - Leaving
```

**Comment by wimpers** [comment]
@khenderick  can we also update this to info as default.

**Comment by khenderick** [comment]
Fxied in #259, packaged in openvstorage-sdm-1.9.1-dev.1498659088.568238d

**Comment by JeffreyDevloo** [comment]
openvstorage-sdm_1.9.1-1_amd64.deb
