### ISSUE TITLE
make it easy to change the loglevel for asd-manager/watcher

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba-asdmanager#258]
Can you make it easier to change the loglevel of all the asd-managers / asd-watchers with one config?
Some key in the config arakoon?

At this moment we need to change manually the level in /opt/asd-manager/source/tools/log_handler.py.

**Comment by JeffreyDevloo** [comment]
Related to: https://github.com/openvstorage/alba-asdmanager/issues/257
Identical fix so closing this one down in favor of the other
