### ISSUE TITLE
[Dual controller] Adjust ASD Manager Setup

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba-asdmanager#318]
Extend the ASD manager setup with the option to configure an IPMI IP, IPMI username and password (default is empty which means nothing gets stored in osvdb)

The IPMI IP, login and password are stored as json` {"ip": "10.100.188.31", "username": "root",  "password": "xz00NNHH8xr8AIJO9CN0Q3rZ0CdZWZAe"}` under /`ovs/alba/asdnodes/<ASD Node  ID>/config/ipmi` in the ovsdb.

**Comment by simonOpenV** [comment]
Are these values supposed to be stored in/ read from an existing preconfig file or in a seperate file?

**Comment by wimpers** [comment]
user needs to enter them during asd manager setup.

**Comment by simonOpenV** [comment]
Options to integrate IPMI info will be:
- Either provide info in the already existing asd-manager preconfig file as another key (mainly used to let installs proceed automated)
- If no info provided in the preconfig file, the interactive input can be used. no input will result in an empty IPMI config file, input will store the input data in the ovsdb.

**Comment by simonOpenV** [comment]
Fixed in #321 
Package info: openvstorage-backend_1.12.0-dev.1518795303.286a148-1

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/alba-asdmanager/releases/tag/1.13.0
