### ISSUE TITLE
[Dual Controller] Initialise devices

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba-asdmanager#322]
To turn a disk into a usable (HA) ASD following actions need to be executed on a dual controller object (parameter list of device id): 

When this API  is called in parallel the /alba/nodes/{guid}/initialize_disks/ on both ASD nodes, one with as initialize_mode parameter active (default if not specified so current flow can still be used) and once as parameter passive. This is an atomic action (per device): both success or a rollback is executed.

Initialize (Active) an ASD with the Primary ASD manager
- Registers the device and ASD in the SQLite
- In arakoon register asd belongs to asd manager
- Create the fstab entry `_entry = '{0}  {1}  xfs  defaults,nofail,noatime,discard,noauto  0  2'`
- Create the ASD process on the controller (systemd)
 - ExecStartPre= 
  - Check if the asd belongs to the local asds manager
  - Fetch local ASD node_id from bootstrap.json
  - Compare with node_id in /ovs/alba/asds/<asd_id>/config
  - If equal puts a file system (xfs) on the disk if not done yet, Mounts the disk (mount /mnt/alba-asd/ ...)
  - If not equal  Stop service and log error that ASD being started  doesn’t belong to the ASD manager.
 -  ExecStopPost= unmount the disk (umount ...)

Initialize (Passive) an ASD with the Secondary ASD manager
- Registers the device and ASD in the SQLite
- Create the fstab entry (see above)
- Creates the ASD service file on the controller (see above)

https://docs.google.com/document/d/1Jzptv2gkq7xbnStq9r93fHsT8Yfw8qo4_1hYyzfilqc

**Comment by dejonghb** [comment]
nofail shouldn't be part of the fstab entry, cfr. google doc where it's removed

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/alba-asdmanager/releases/tag/1.13.0
