### ISSUE TITLE
rocksdb_block_cache_size is wrong

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba-asdmanager#334]
### Problem description
This indicates the memory reserved for memory within asds. Current calculation is https://github.com/openvstorage/alba-asdmanager/blame/develop/source/controllers/asd.py#L76

@toolslive what are your thoughts?

**Comment by toolslive** [comment]
the block cache is where RocksDB caches data in memory for reads.
the default (if you don't configure anything) is determined as follows:
```
(* 
     * we write multiple key value pairs to rocksdb per fragment,
     * but only one of these should be cached.
     * This key value pair has the following size:
     * - key = 1 (asd) + 1+4+1+4 (namespace prefix) + 1+4+32+4+4+4 (object/fragment identification) = 60 bytes
     * - value = 1+4 (crc32) + 1+8+4 (fnr+size) = 18
     *
     * assuming another 8 bytes of overhead by rocksdb then we get in total 86 bytes
     * that should be cached per fragment
     *
     * some notes:
     * - block cache is uncompressed
     * - there are other keys (gc tag) that also pollute the cache when deleting them
     * - we can still optimize the object_id size from 32 bytes down to 8
     *
     * so let's go for 100 bytes per 1_000_000 of capacity
*)
(Int64.to_float capacity) /. 10_000. |> int_of_float
```
your code calculations put ~930MB for a 4TB HDD, and ~120MB for an 512GB SSD.
This is too large for an HDD, and about right for an SSD, but ....
I guess you also want to take into account the maximum memory you allow the ASD to consume.
I would not go beyond 25% of the alloted ASD memory consumption.

**Comment by simonOpenV** [comment]
#### Will be fixed by: 
https://github.com/openvstorage/alba-asdmanager/pull/335

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/alba-asdmanager/releases/tag/1.13.0
