### ISSUE TITLE
unattended installation file for alba-asdmanager should seperated from openvstorage

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#74]
Current situation is, located in `/opt/OpenvStorage/config/openvstorage_preconfig.json`: 

```
{
 "setup":
    {
        "master_ip": "1.2.3.4",
        "node_type": "extra",
        "cluster_ip": "1.2.3.5",
        "master_password": "my_master_pass",
        "hypervisor_ip": "1.2.3.1",
        "hypervisor_name": "esx1",
        "hypervisor_username": "root",
        "hypervisor_password": "esx_pass",
        "hypervisor_type": "VMWARE"
    },
 "asdmanager":
    {
        "api_ip": "1.2.3.5"
    }
}
```

The `asdmanager` part should be in another file because of hyperscale / geoscale. e.g. `/opt/asd-manager/config/asd_manager_preconfig.json`

```
{
 "asdmanager":
    {
        "api_ip": "1.2.3.5"
    }
}
```

**Comment by wimpers** [comment]
@khenderick  is there a reason why this would not be possible? Any reason why they are combined?

**Comment by kvanhijf** [comment]
@wimpers , this is possible and there is no specific reason why they are combined
During integration looked over the fact that the ASD manager setup can run independently of OVS
So, this is still a valid ticket to be handled

**Comment by khenderick** [comment]
Was already implemented a while back

**Comment by JeffreyDevloo** [comment]
### Information
The asd-manager config is currently in /opt/asd-manager/config/preconfig.json.
OVS config is currently in /opt/OpenvStorage/config/preconfig.json

### Test result
Test passed. The configuration files are in a seperate file.
