### ISSUE TITLE
python-requests package is missing when installing openvstorage-sdm

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#88]
When trying to start the setup of openvstorage-sdm, it does not work because the python-requests package is missing

**Comment by khenderick** [comment]
Fixed by #100, available in openvstorage-sdm-1.6.3-rev.346.3c58610, fixed by @kinvaris

**Comment by JeffreyDevloo** [comment]
During multiple installs of the OVH environment, we were unable to reproduce this issue.

### Steps
- Ran ovs setup (attended and unattended)
- Installed sdm or storage nodes

### Output
All sdm installs were succesfull.
