### ISSUE TITLE
A configured but failing disk cannot be restarted

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba-asdmanager#93]
A configured but failing disk cannot be restarted

**Comment by khenderick** [comment]
Forgot verification step.

**Comment by deepshirsath** [comment]
**PASSED** on **Open vStorage: 2.7.1-fargo.1-1**

Open vStorage: 2.7.1-fargo.1-1
Open vStorage - Backend: 1.7.1-fargo.1-1
Open vStorage - SDM: 1.6.1-fargo.1-1
Storage Driver - Base: 6.0.3-dev.201607191821.0758481
Storage Driver - Server: 6.0.3-dev.201607191821.0758481
Alba: 0.9.14
Arakoon 1.9.8

- Failing plus configured disk can be re-started via OVS gui console. ( see screenshots)

![failed-disk](https://cloud.githubusercontent.com/assets/14201912/18053278/440307d0-6e1c-11e6-9179-b351a96b2a00.PNG)


![failed-disk-ovs-gui](https://cloud.githubusercontent.com/assets/14201912/18053288/4ad56ada-6e1c-11e6-90bc-ffd1455b00c2.PNG)


![failed-disk-able-to-restart](https://cloud.githubusercontent.com/assets/14201912/18053301/54b129b8-6e1c-11e6-9139-dbea4b9cfb04.png)
